create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  full_name text,
  role text not null default 'representant' check (role in ('representant', 'manager', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_app_users_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_app_users_updated_at on public.app_users;
create trigger trg_app_users_updated_at
before update on public.app_users
for each row
execute function public.set_app_users_updated_at();

alter table public.app_users enable row level security;

drop policy if exists "Deny all app users direct access" on public.app_users;
create policy "Deny all app users direct access"
on public.app_users
for all
using (false)
with check (false);

insert into public.app_users (email, full_name, role, is_active)
values
  ('admin@hondabrossard.com', 'Admin Honda', 'admin', true)
on conflict (email) do update
set
  full_name = excluded.full_name,
  role = excluded.role,
  is_active = excluded.is_active,
  updated_at = now();
