create table if not exists public.simulation_runs (
  id bigint generated by default as identity primary key,
  user_email text not null,
  user_name text,
  level text,
  goal text,
  outcome text,
  client_name text,
  client_segment text,
  client_difficulty text,
  transcript jsonb not null default '[]'::jsonb,
  evaluation jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_simulation_runs_user_email_created_at
  on public.simulation_runs (user_email, created_at desc);

alter table public.simulation_runs enable row level security;

drop policy if exists "Deny all simulation runs direct access" on public.simulation_runs;
create policy "Deny all simulation runs direct access"
on public.simulation_runs
for all
using (false)
with check (false);
