create table if not exists public.client_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  segment text not null,
  difficulty text not null check (difficulty in ('Débutant','Intermédiaire','Avancé')),
  persona text not null,
  needs text not null,
  objections text not null,
  budget_range text not null,
  urgency text not null,
  trade_in text not null,
  financing_preference text not null,
  sales_strategy text not null,
  created_at timestamptz not null default now()
);

alter table public.client_profiles enable row level security;

drop policy if exists "Public read client profiles" on public.client_profiles;
create policy "Public read client profiles"
on public.client_profiles
for select
using (true);

insert into public.client_profiles
(name, segment, difficulty, persona, needs, objections, budget_range, urgency, trade_in, financing_preference, sales_strategy)
values
('Famille pragmatique','Famille','Intermédiaire','Couple avec un enfant, veut un VUS polyvalent sans dépasser le budget mensuel.','Espace, sécurité, fiabilité, paiement stable.','Paiement trop élevé, peur des frais cachés.','550-700 CAD/mois','30 jours','Hyundai Elantra 2018','Hésite entre achat et location','Découverte structurée + comparaison claire de 2 options max + cadrage des coûts totaux.'),
('Navetteur analytique','Solo','Intermédiaire','Professionnel qui roule beaucoup et compare 2-3 marques de manière rationnelle.','Consommation, coût total, transparence.','Sceptique sur les frais concession.','450-600 CAD/mois','2-6 semaines','Aucun','Financement','Utiliser des chiffres simples, preuves concrètes et réponses factuelles sans pression.'),
('Client pressé','Urgence','Débutant','Besoin d''un véhicule très vite, peu de temps pour magasiner.','Disponibilité rapide, processus efficace.','Peur de perdre du temps.','600-850 CAD/mois','Cette semaine','SUV 2017','Ouvert','Diriger la vente par étapes courtes, confirmer rapidement la prochaine action.'),
('Acheteur prix d''abord','Prix','Intermédiaire','Ne parle presque que du paiement mensuel et du rabais.','Mensualité basse, clarté.','Se méfie des extras ajoutés à la fin.','400-550 CAD/mois','15-30 jours','Compacte 2016','Location','Recentrer sur valeur/coût total et proposer 2 scénarios de paiement transparents.'),
('Client sceptique','Confiance','Avancé','Mauvaise expérience passée en concession, faible confiance au départ.','Preuve de transparence, respect.','Crainte de se faire pousser.','500-750 CAD/mois','30-45 jours','Berline 2015','Financement','Empathie + permission + validation fréquente; zéro pression et engagement progressif.'),
('Jeune premier achat','Nouveau conducteur','Débutant','Premier achat auto, anxieux face au financement.','Éducation, simplicité, sécurité.','Ne comprend pas bien location vs achat.','350-500 CAD/mois','2 mois','Aucun','Indécis','Éduquer sans jargon, reformuler souvent, faire valider chaque étape.'),
('Client fidélité marque','Fidélisation','Intermédiaire','Possède déjà une Honda, veut upgrader mais hésite sur le moment.','Valeur de reprise, nouveauté utile.','Peut attendre encore 1 an.','550-800 CAD/mois','Flexible','Honda Civic 2020','Financement','Capitaliser sur historique positif + démontrer gains concrets de l''upgrade.'),
('Client orienté techno','Technologie','Avancé','Veut les fonctions avancées et compare les versions en détail.','Aides à la conduite, connectivité.','Peur de payer trop pour des options inutiles.','650-900 CAD/mois','3-5 semaines','Aucun','Location','Qualifier les vrais usages techno, démontrer la valeur par cas concret.'),
('Client flotte PME','B2B','Avancé','Propriétaire de PME, regarde 2 véhicules pour son équipe.','Fiabilité, coûts prévisibles, service.','Négociation ferme sur volume.','Variable','4-8 semaines','Pick-up 2019','Financement','Approche consultative business, chiffrage total et suivi structuré.'),
('Client indécis chronique','Décision','Avancé','Passe d''un modèle à l''autre, peur de regretter.','Clarté décisionnelle, comparaison nette.','Repousse la décision.','500-700 CAD/mois','Aucune','Mazda 2017','Indécis','Limiter les options, utiliser critères pondérés et conclure avec next step datée.')
on conflict do nothing;
