create table if not exists public.training_module_runs (
  id bigint generated by default as identity primary key,
  user_email text not null,
  user_name text,
  topic_slug text not null,
  topic_title text not null,
  level text,
  status text not null default 'completed',
  context_summary text,
  transcript jsonb not null default '[]'::jsonb,
  evaluation jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_training_module_runs_user_email_created_at
  on public.training_module_runs (user_email, created_at desc);

alter table public.training_module_runs enable row level security;

drop policy if exists "Deny all training module runs direct access" on public.training_module_runs;
create policy "Deny all training module runs direct access"
on public.training_module_runs
for all
using (false)
with check (false);
