create table if not exists public.client_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  segment text not null,
  difficulty text not null check (difficulty in ('DÃƒÆ’Ã‚Â©butant','IntermÃƒÆ’Ã‚Â©diaire','AvancÃƒÆ’Ã‚Â©')),
  persona text not null,
  needs text not null,
  objections text not null,
  budget_range text not null,
  urgency text not null,
  trade_in text not null,
  financing_preference text not null,
  sales_strategy text not null,
  created_at timestamptz not null default now()
);

alter table public.client_profiles enable row level security;

drop policy if exists "Public read client profiles" on public.client_profiles;
create policy "Public read client profiles"
on public.client_profiles
for select
using (true);

insert into public.client_profiles
(name, segment, difficulty, persona, needs, objections, budget_range, urgency, trade_in, financing_preference, sales_strategy)
values
('Famille pragmatique','Famille','IntermÃƒÆ’Ã‚Â©diaire','Couple avec un enfant, veut un VUS polyvalent sans dÃƒÆ’Ã‚Â©passer le budget mensuel.','Espace, sÃƒÆ’Ã‚Â©curitÃƒÆ’Ã‚Â©, fiabilitÃƒÆ’Ã‚Â©, paiement stable.','Paiement trop ÃƒÆ’Ã‚Â©levÃƒÆ’Ã‚Â©, peur des frais cachÃƒÆ’Ã‚Â©s.','550-700 CAD/mois','30 jours','Hyundai Elantra 2018','HÃƒÆ’Ã‚Â©site entre achat et location','DÃƒÆ’Ã‚Â©couverte structurÃƒÆ’Ã‚Â©e + comparaison claire de 2 options max + cadrage des coÃƒÆ’Ã‚Â»ts totaux.'),
('Navetteur analytique','Solo','IntermÃƒÆ’Ã‚Â©diaire','Professionnel qui roule beaucoup et compare 2-3 marques de maniÃƒÆ’Ã‚Â¨re rationnelle.','Consommation, coÃƒÆ’Ã‚Â»t total, transparence.','Sceptique sur les frais concession.','450-600 CAD/mois','2-6 semaines','Aucun','Financement','Utiliser des chiffres simples, preuves concrÃƒÆ’Ã‚Â¨tes et rÃƒÆ’Ã‚Â©ponses factuelles sans pression.'),
('Client pressÃƒÆ’Ã‚Â©','Urgence','DÃƒÆ’Ã‚Â©butant','Besoin d''un vÃƒÆ’Ã‚Â©hicule trÃƒÆ’Ã‚Â¨s vite, peu de temps pour magasiner.','DisponibilitÃƒÆ’Ã‚Â© rapide, processus efficace.','Peur de perdre du temps.','600-850 CAD/mois','Cette semaine','SUV 2017','Ouvert','Diriger la vente par ÃƒÆ’Ã‚Â©tapes courtes, confirmer rapidement la prochaine action.'),
('Acheteur prix d''abord','Prix','IntermÃƒÆ’Ã‚Â©diaire','Ne parle presque que du paiement mensuel et du rabais.','MensualitÃƒÆ’Ã‚Â© basse, clartÃƒÆ’Ã‚Â©.','Se mÃƒÆ’Ã‚Â©fie des extras ajoutÃƒÆ’Ã‚Â©s ÃƒÆ’Ã‚Â  la fin.','400-550 CAD/mois','15-30 jours','Compacte 2016','Location','Recentrer sur valeur/coÃƒÆ’Ã‚Â»t total et proposer 2 scÃƒÆ’Ã‚Â©narios de paiement transparents.'),
('Client sceptique','Confiance','AvancÃƒÆ’Ã‚Â©','Mauvaise expÃƒÆ’Ã‚Â©rience passÃƒÆ’Ã‚Â©e en concession, faible confiance au dÃƒÆ’Ã‚Â©part.','Preuve de transparence, respect.','Crainte de se faire pousser.','500-750 CAD/mois','30-45 jours','Berline 2015','Financement','Empathie + permission + validation frÃƒÆ’Ã‚Â©quente; zÃƒÆ’Ã‚Â©ro pression et engagement progressif.'),
('Jeune premier achat','Nouveau conducteur','DÃƒÆ’Ã‚Â©butant','Premier achat auto, anxieux face au financement.','ÃƒÆ’Ã¢â‚¬Â°ducation, simplicitÃƒÆ’Ã‚Â©, sÃƒÆ’Ã‚Â©curitÃƒÆ’Ã‚Â©.','Ne comprend pas bien location vs achat.','350-500 CAD/mois','2 mois','Aucun','IndÃƒÆ’Ã‚Â©cis','ÃƒÆ’Ã¢â‚¬Â°duquer sans jargon, reformuler souvent, faire valider chaque ÃƒÆ’Ã‚Â©tape.'),
('Client fidÃƒÆ’Ã‚Â©litÃƒÆ’Ã‚Â© marque','FidÃƒÆ’Ã‚Â©lisation','IntermÃƒÆ’Ã‚Â©diaire','PossÃƒÆ’Ã‚Â¨de dÃƒÆ’Ã‚Â©jÃƒÆ’Ã‚Â  une Honda, veut upgrader mais hÃƒÆ’Ã‚Â©site sur le moment.','Valeur de reprise, nouveautÃƒÆ’Ã‚Â© utile.','Peut attendre encore 1 an.','550-800 CAD/mois','Flexible','Honda Civic 2020','Financement','Capitaliser sur historique positif + dÃƒÆ’Ã‚Â©montrer gains concrets de l''upgrade.'),
('Client orientÃƒÆ’Ã‚Â© techno','Technologie','AvancÃƒÆ’Ã‚Â©','Veut les fonctions avancÃƒÆ’Ã‚Â©es et compare les versions en dÃƒÆ’Ã‚Â©tail.','Aides ÃƒÆ’Ã‚Â  la conduite, connectivitÃƒÆ’Ã‚Â©.','Peur de payer trop pour des options inutiles.','650-900 CAD/mois','3-5 semaines','Aucun','Location','Qualifier les vrais usages techno, dÃƒÆ’Ã‚Â©montrer la valeur par cas concret.'),
('Client flotte PME','B2B','AvancÃƒÆ’Ã‚Â©','PropriÃƒÆ’Ã‚Â©taire de PME, regarde 2 vÃƒÆ’Ã‚Â©hicules pour son ÃƒÆ’Ã‚Â©quipe.','FiabilitÃƒÆ’Ã‚Â©, coÃƒÆ’Ã‚Â»ts prÃƒÆ’Ã‚Â©visibles, service.','NÃƒÆ’Ã‚Â©gociation ferme sur volume.','Variable','4-8 semaines','Pick-up 2019','Financement','Approche consultative business, chiffrage total et suivi structurÃƒÆ’Ã‚Â©.'),
('Client indecis chronique','Decision','Avance','Passe d''un modele a l''autre, peur de regretter.','Clarte decisionnelle, comparaison nette.','Repousse la decision.','500-700 CAD/mois','Aucune','Mazda 2017','Indecis','Limiter les options, utiliser criteres ponderes et conclure avec next step datee.'),
('Chauffeur Uber budget serre','Mobilite urbaine','IntermÃƒÆ’Ã‚Â©diaire','Cherche un vehicule pour faire du Uber avec budget tres serre.','Paiement bas, fiabilite mecanique, confort passagers, bonne consommation.','Craint les couts d entretien et doute de la rentabilite.','350-450 CAD/mois','2-4 semaines','Berline 2014','Financement','Valider kilometrage annuel, presenter options economiques et cout total mensuel clair.'),
('Explorateur multi-marques Taschereau','Exploration','DÃƒÆ’Ã‚Â©butant','Debut de magasinage sur le boulevard Taschereau, compare plusieurs marques.','Infos simples, comparaison rapide, premiere impression positive.','Ne veut pas s engager, dit qu il magasine seulement.','500-750 CAD/mois','1-3 mois','Aucun','IndÃƒÆ’Ã‚Â©cis','Approche consultation, questions ouvertes courtes et proposition d une prochaine etape sans pression.'),
('Visite eclair indecis','Temps limite','AvancÃƒÆ’Ã‚Â©','Entre pour des infos sommaires, peu de temps, besoins et budget flous.','Discussion ultra concise, clarte, orientation rapide.','Impatient, reponses courtes, difficile a faire progresser.','Budget inconnu','Non defini','Vehicule actuel inconnu','IndÃƒÆ’Ã‚Â©cis','Qualifier en 3 questions prioritaires, proposer mini-plan et prise de rendez-vous court.')on conflict do nothing;
